title: Kuma's Diary
description: My tech blog.
theme: just-the-docs
url: https://huang-pixel.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607
